version: '3'

services:

    appariement:
        image: webclient:appariement
        container_name: appariement
        networks:
            testing_net:
                ipv4_address: 172.28.0.253


    partie:
        image: webclient:partie
        container_name: partie
        environment:
            - SERVER_IP=http://172.28.0.253:8080/
            - SERVER_PORT=8090
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3
        depends_on:
            - appariement
#    proba:
#        image: webclient:proba
#        container_name: proba
#        environment:
#            - SERVER_IP=http://172.28.0.253:8080/
#            - SERVER_PORT=8091
#        networks:
#            testing_net:
#            #  ipv4_address: 172.28.0.3
#        depends_on:
#            - appariement

    michel:
        image: webclient:joueur
        container_name: michel
        environment:
            - SERVER_IP=http://172.28.0.253:8080/
            - NOM=MICHEL
            - SERVER_PORT=8081
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3
        depends_on:
            - partie


    greg:
        image: webclient:joueur
        container_name: greg
        environment:
            - SERVER_IP=http://172.28.0.253:8080/
            - NOM=GREG
            - SERVER_PORT=8082
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3
        depends_on:
            - michel
    maxime:
        image: webclient:joueur
        container_name: maxime
        environment:
            - SERVER_IP=http://172.28.0.253:8080/
            - NOM=MAXIME
            - SERVER_PORT=8083
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3
        depends_on:
            - greg
    krimi:
        image: webclient:joueur
        container_name: krimi
        environment:
            - SERVER_IP=http://172.28.0.253:8080/
            - NOM=KRIMI
            - SERVER_PORT=8084
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3
        depends_on:
            - maxime
    diallo:
        image: webclient:joueur
        container_name: diallo
        environment:
            - SERVER_IP=http://172.28.0.253:8080/
            - NOM=DIALLO
            - LANCEMENT=true
            - SERVER_PORT=8085
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3
        depends_on:
            - krimi


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
