version: '3.9'

services:

    serveur:
        image: zeroo
        container_name: appariement
        networks:
            testing_net:
                ipv4_address: 172.28.0.253
        depends_on:
            - client

    client:
        image: zero
        # container_name: hebergeur
        environment:
            - SERVER_IP=172.28.0.253
        networks:
            testing_net:
            #  ipv4_address: 172.28.0.3


networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16